// Code generated by protoc-gen-go. DO NOT EDIT.
// source: student/studentpb/student.proto

package studentpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Student) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

//register student
type RegisterStudentRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterStudentRequest) Reset()         { *m = RegisterStudentRequest{} }
func (m *RegisterStudentRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterStudentRequest) ProtoMessage()    {}
func (*RegisterStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{1}
}

func (m *RegisterStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterStudentRequest.Unmarshal(m, b)
}
func (m *RegisterStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterStudentRequest.Marshal(b, m, deterministic)
}
func (m *RegisterStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStudentRequest.Merge(m, src)
}
func (m *RegisterStudentRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterStudentRequest.Size(m)
}
func (m *RegisterStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStudentRequest proto.InternalMessageInfo

func (m *RegisterStudentRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type RegisterStudentResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterStudentResponse) Reset()         { *m = RegisterStudentResponse{} }
func (m *RegisterStudentResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterStudentResponse) ProtoMessage()    {}
func (*RegisterStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{2}
}

func (m *RegisterStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterStudentResponse.Unmarshal(m, b)
}
func (m *RegisterStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterStudentResponse.Marshal(b, m, deterministic)
}
func (m *RegisterStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStudentResponse.Merge(m, src)
}
func (m *RegisterStudentResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterStudentResponse.Size(m)
}
func (m *RegisterStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStudentResponse proto.InternalMessageInfo

func (m *RegisterStudentResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

//get student list
type GetStudentListRequest struct {
	CollegeName          string   `protobuf:"bytes,1,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentListRequest) Reset()         { *m = GetStudentListRequest{} }
func (m *GetStudentListRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentListRequest) ProtoMessage()    {}
func (*GetStudentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{3}
}

func (m *GetStudentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentListRequest.Unmarshal(m, b)
}
func (m *GetStudentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentListRequest.Marshal(b, m, deterministic)
}
func (m *GetStudentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentListRequest.Merge(m, src)
}
func (m *GetStudentListRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudentListRequest.Size(m)
}
func (m *GetStudentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentListRequest proto.InternalMessageInfo

func (m *GetStudentListRequest) GetCollegeName() string {
	if m != nil {
		return m.CollegeName
	}
	return ""
}

type GetStudentListResponse struct {
	StudentName          string   `protobuf:"bytes,1,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	CollegeName          string   `protobuf:"bytes,2,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentListResponse) Reset()         { *m = GetStudentListResponse{} }
func (m *GetStudentListResponse) String() string { return proto.CompactTextString(m) }
func (*GetStudentListResponse) ProtoMessage()    {}
func (*GetStudentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e507e88556d669a, []int{4}
}

func (m *GetStudentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentListResponse.Unmarshal(m, b)
}
func (m *GetStudentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentListResponse.Marshal(b, m, deterministic)
}
func (m *GetStudentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentListResponse.Merge(m, src)
}
func (m *GetStudentListResponse) XXX_Size() int {
	return xxx_messageInfo_GetStudentListResponse.Size(m)
}
func (m *GetStudentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentListResponse proto.InternalMessageInfo

func (m *GetStudentListResponse) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *GetStudentListResponse) GetCollegeName() string {
	if m != nil {
		return m.CollegeName
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "student.Student")
	proto.RegisterType((*RegisterStudentRequest)(nil), "student.RegisterStudentRequest")
	proto.RegisterType((*RegisterStudentResponse)(nil), "student.RegisterStudentResponse")
	proto.RegisterType((*GetStudentListRequest)(nil), "student.GetStudentListRequest")
	proto.RegisterType((*GetStudentListResponse)(nil), "student.GetStudentListResponse")
}

func init() {
	proto.RegisterFile("student/studentpb/student.proto", fileDescriptor_6e507e88556d669a)
}

var fileDescriptor_6e507e88556d669a = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x3d, 0xb4, 0x66, 0x52, 0x54, 0x06, 0x8c, 0x52, 0xd1, 0xb4, 0x39, 0x89, 0x87, 0xaa,
	0xf5, 0xe6, 0x51, 0x14, 0x2f, 0xe2, 0x21, 0x05, 0x0f, 0x1e, 0x94, 0xb4, 0x8e, 0x21, 0x90, 0x26,
	0x71, 0x67, 0xe3, 0xaf, 0xf3, 0xc7, 0x49, 0xb7, 0xb3, 0x4b, 0x3f, 0x4f, 0xbb, 0xfb, 0xde, 0xcc,
	0x9b, 0x37, 0x8f, 0x85, 0x88, 0x75, 0xf3, 0x45, 0xa5, 0xbe, 0x96, 0xb3, 0x9e, 0xd8, 0xdb, 0xb0,
	0x56, 0x95, 0xae, 0xb0, 0x23, 0xcf, 0xf8, 0x09, 0x3a, 0xe3, 0xc5, 0x15, 0xcf, 0x01, 0xbe, 0x73,
	0xc5, 0xfa, 0xb3, 0x4c, 0x67, 0x74, 0xea, 0xf5, 0xbd, 0x4b, 0x3f, 0xf1, 0x0d, 0xf2, 0x9a, 0xce,
	0x08, 0xcf, 0xc0, 0x2f, 0x52, 0xcb, 0xb6, 0x0c, 0xbb, 0x3f, 0x07, 0xe6, 0x64, 0xfc, 0x08, 0x61,
	0x42, 0x59, 0xce, 0x9a, 0x94, 0xc8, 0x25, 0xf4, 0xd3, 0x10, 0x6b, 0xbc, 0x02, 0x3b, 0xcb, 0x48,
	0x06, 0xa3, 0xa3, 0xa1, 0xb5, 0x62, 0x2b, 0x9d, 0x99, 0x5b, 0x38, 0xd9, 0x50, 0xe1, 0xba, 0x2a,
	0x99, 0x30, 0x84, 0xb6, 0x22, 0x6e, 0x0a, 0x2d, 0xc6, 0xe4, 0x15, 0xdf, 0xc3, 0xf1, 0x33, 0x69,
	0xa9, 0x7e, 0xc9, 0xd9, 0xcd, 0x1d, 0x40, 0x77, 0x5a, 0x15, 0x05, 0x65, 0xb4, 0xbc, 0x4f, 0x20,
	0x98, 0x31, 0xfd, 0x01, 0xe1, 0x7a, 0xaf, 0x4c, 0x1b, 0x40, 0x57, 0x3c, 0xad, 0x34, 0x0b, 0x66,
	0xe2, 0x58, 0xd7, 0x6f, 0x6d, 0xe8, 0x8f, 0xfe, 0x3c, 0x38, 0x10, 0xf5, 0x31, 0xa9, 0xdf, 0x7c,
	0x4a, 0xf8, 0x06, 0x87, 0x6a, 0x75, 0x43, 0x8c, 0x5c, 0x1e, 0xdb, 0x13, 0xec, 0xf5, 0x77, 0x17,
	0x2c, 0xec, 0xc6, 0x7b, 0x98, 0x40, 0x90, 0xb9, 0x55, 0x18, 0x2f, 0x5c, 0xcb, 0xd6, 0x70, 0x7a,
	0xd1, 0x4e, 0xde, 0x2a, 0xde, 0x78, 0x0f, 0xc1, 0xbb, 0xef, 0xbe, 0xcf, 0xa4, 0x6d, 0xfe, 0xcd,
	0xdd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xfe, 0xdc, 0x5b, 0x5a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	//unary
	RegisterStudent(ctx context.Context, in *RegisterStudentRequest, opts ...grpc.CallOption) (*RegisterStudentResponse, error)
	//server streaming
	GetStudents(ctx context.Context, in *GetStudentListRequest, opts ...grpc.CallOption) (StudentService_GetStudentsClient, error)
}

type studentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServiceClient(cc grpc.ClientConnInterface) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) RegisterStudent(ctx context.Context, in *RegisterStudentRequest, opts ...grpc.CallOption) (*RegisterStudentResponse, error) {
	out := new(RegisterStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/registerStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetStudents(ctx context.Context, in *GetStudentListRequest, opts ...grpc.CallOption) (StudentService_GetStudentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StudentService_serviceDesc.Streams[0], "/student.StudentService/getStudents", opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceGetStudentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StudentService_GetStudentsClient interface {
	Recv() (*GetStudentListResponse, error)
	grpc.ClientStream
}

type studentServiceGetStudentsClient struct {
	grpc.ClientStream
}

func (x *studentServiceGetStudentsClient) Recv() (*GetStudentListResponse, error) {
	m := new(GetStudentListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	//unary
	RegisterStudent(context.Context, *RegisterStudentRequest) (*RegisterStudentResponse, error)
	//server streaming
	GetStudents(*GetStudentListRequest, StudentService_GetStudentsServer) error
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) RegisterStudent(ctx context.Context, req *RegisterStudentRequest) (*RegisterStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStudent not implemented")
}
func (*UnimplementedStudentServiceServer) GetStudents(req *GetStudentListRequest, srv StudentService_GetStudentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStudents not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_RegisterStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).RegisterStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/RegisterStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).RegisterStudent(ctx, req.(*RegisterStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetStudents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStudentListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StudentServiceServer).GetStudents(m, &studentServiceGetStudentsServer{stream})
}

type StudentService_GetStudentsServer interface {
	Send(*GetStudentListResponse) error
	grpc.ServerStream
}

type studentServiceGetStudentsServer struct {
	grpc.ServerStream
}

func (x *studentServiceGetStudentsServer) Send(m *GetStudentListResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "student.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerStudent",
			Handler:    _StudentService_RegisterStudent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getStudents",
			Handler:       _StudentService_GetStudents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "student/studentpb/student.proto",
}
